use_frameworks!

platform :ios, '9.3'

target 'RxRelay-PropertyWrappers_Example' do
  pod 'RxRelay-PropertyWrappers', :path => '../'

  target 'RxRelay-PropertyWrappers_Tests' do
    inherit! :search_paths
  end
end
