use_frameworks!

platform :ios, '10.0'

target 'RxRelay-PropertyWrappers_Example' do
  pod 'RxRelay-PropertyWrappers', :path => '../'

  target 'RxRelay-PropertyWrappers_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
